import streamlit as st

st.markdown('''
# ARE YOU READY FOR YOUR JOURNEY TOWARDS FINANCIAL FREEDOM?
# WITH MY APP YOU CAN MAKE INFORMED INVESTMENT DECISIONS TO MAXIMIZE YOUR RETURNS!
# THANK YOU FOR YOUR TIME!
# ANY QUESTIONS?
''')
st.write('---')
